# Generated by Django 3.1.6 on 2021-02-24 03:30

import content.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('content', '0002_auto_20210220_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Date')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Modified Dtae')),
                ('name', models.CharField(default='Default Setting', max_length=100, verbose_name='Name')),
                ('home_page_image', models.ImageField(blank=True, null=True, upload_to='catalog/images', verbose_name='Home Page Image')),
                ('login_image', models.ImageField(blank=True, null=True, upload_to='catalog/images', verbose_name='Login Image')),
                ('registration_image', models.ImageField(blank=True, null=True, upload_to='catalog/images', verbose_name='Registration Image')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.flatpage')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Date')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Modified Dtae')),
                ('display_order', models.IntegerField(blank=True, default=content.models.FlatPageExt.get_default_order, help_text='Used to order the display', null=True, verbose_name='Display Order')),
                ('type', models.CharField(blank=True, choices=[('discover', 'Display in Discover section')], max_length=50, null=True, verbose_name='Page Type')),
            ],
            options={
                'ordering': ('display_order', 'title'),
                'abstract': False,
            },
            bases=('flatpages.flatpage', models.Model),
        ),
        migrations.RemoveField(
            model_name='media',
            name='language',
        ),
        migrations.AddField(
            model_name='media',
            name='description_en',
            field=models.TextField(blank=True, help_text='Provide a brief description about the Music', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='media',
            name='description_fr',
            field=models.TextField(blank=True, help_text='Provide a brief description about the Music', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='media',
            name='internal_link_en',
            field=models.FileField(blank=True, help_text='Use this field if the Music file is store Internally to this application', null=True, upload_to='catalog/music', verbose_name='Music File'),
        ),
        migrations.AddField(
            model_name='media',
            name='internal_link_fr',
            field=models.FileField(blank=True, help_text='Use this field if the Music file is store Internally to this application', null=True, upload_to='catalog/music', verbose_name='Music File'),
        ),
        migrations.AddField(
            model_name='media',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='media',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='media',
            name='url_link_en',
            field=models.CharField(blank=True, help_text='Use this field if the Music file is store externally to this application', max_length=255, null=True, verbose_name='External Url'),
        ),
        migrations.AddField(
            model_name='media',
            name='url_link_fr',
            field=models.CharField(blank=True, help_text='Use this field if the Music file is store externally to this application', max_length=255, null=True, verbose_name='External Url'),
        ),
    ]
