# Generated by Django 3.1.6 on 2021-02-26 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('content', '0004_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('O', 'Other')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='transaction_ref_model',
            field=models.ForeignKey(blank=True, help_text='Models to which this Transaction referred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='contenttypes.contenttype', verbose_name='Transaction Reference Model'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
