# Generated by Django 3.1.6 on 2021-02-26 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('content', '0005_auto_20210225_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'get_latest_by': 'created', 'ordering': ('created',)},
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='deposit',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='transaction_ref_id',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='transaction_ref_model',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='transcation_date',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='withdraw',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Date')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Modified Dtae')),
                ('deposit', models.FloatField(verbose_name='Deposit Amount')),
                ('withdraw', models.FloatField(verbose_name='Withdraw Amount')),
                ('transcation_date', models.DateTimeField(verbose_name='Transaction Date')),
                ('transaction_ref_id', models.IntegerField(blank=True, null=True, verbose_name='Transaction Reference Id')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='currency_transaction', to='content.currency', verbose_name='Currency')),
                ('transaction_ref_model', models.ForeignKey(blank=True, help_text='Models to which this Transaction referred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='contenttypes.contenttype', verbose_name='Transaction Reference Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Transaction',
                'ordering': ('transcation_date',),
            },
        ),
    ]
