# Generated by Django 3.1.6 on 2021-02-27 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0006_auto_20210225_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Date')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Modified Dtae')),
                ('uid', models.CharField(max_length=20, verbose_name='Uid Name')),
                ('token', models.CharField(max_length=100, verbose_name='Token')),
                ('expiration_date', models.DateTimeField(verbose_name='Expiration Date')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('succes', models.BooleanField(blank=True, null=True, verbose_name='Succes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('attempt', models.IntegerField(default=0, verbose_name='Number of Attempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_users', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('created',),
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
