# Generated by Django 3.1.6 on 2021-03-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='media',
            field=models.ManyToManyField(blank=True, null=True, related_name='media_playlists', to='content.Media', verbose_name='Media'),
        ),
    ]
