# Generated by Django 3.1.6 on 2021-03-04 03:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0008_auto_20210302_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralarmsettings',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='media_playlists', to='content.Media', verbose_name='Media'),
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('user', 'name')},
        ),
    ]
