# Generated by Django 3.1.6 on 2021-03-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20210303_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
