# Generated by Django 3.1.6 on 2021-03-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_message_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
