# Generated by Django 3.1.6 on 2021-03-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20210305_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, help_text='Use this field to set the image that will be displayed in the media player', null=True, upload_to='catalog/images', verbose_name='Audio Player background image'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='msg_listen',
            field=models.BooleanField(verbose_name='Message listened'),
        ),
    ]
