# Generated by Django 3.1.6 on 2021-03-09 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20210308_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='offer_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='content.offerprice', verbose_name='Offer Price'),
        ),
    ]
