# Generated by Django 3.1.6 on 2021-03-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_subscription_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
