# Generated by Django 3.1.6 on 2021-03-21 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20210319_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_ref_model',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Subscription', 'Subscription'), ('Media', 'Media'), ('credit', 'Credit')], max_length=20, null=True, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='currency_transaction', to='content.currency', verbose_name='Currency'),
        ),
    ]
