# Generated by Django 3.1.6 on 2021-03-22 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20210321_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('transaction_type',), 'verbose_name_plural': 'Transaction'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transcation_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction Date'),
        ),
    ]
