# Generated by Django 3.1.6 on 2021-03-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20210322_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Transaction'},
        ),
        migrations.AlterField(
            model_name='credit',
            name='balance',
            field=models.FloatField(blank=True, null=True, verbose_name='Balance'),
        ),
    ]
